import { useState } from 'react'
import { LuBedDouble, LuCheck, LuClipboardList, LuSparkles } from 'react-icons/lu'

type Task = { id: string; room: string; type: 'Cleaning' | 'Inspection' | 'Maintenance'; assignee: string; status: 'Pending' | 'In progress' | 'Completed' }
const initialTasks: Task[] = [
  { id: 'HK-001', room: '102', type: 'Cleaning', assignee: 'Mary N.', status: 'Pending' },
  { id: 'HK-002', room: '202', type: 'Inspection', assignee: 'James K.', status: 'In progress' },
  { id: 'HK-003', room: '105', type: 'Maintenance', assignee: 'Peter O.', status: 'Pending' },
]

export default function Housekeeping() {
  const [tasks, setTasks] = useState(initialTasks)
  const [filter, setFilter] = useState<'All' | Task['status']>('All')
  const visible = filter === 'All' ? tasks : tasks.filter((task) => task.status === filter)
  function advance(task: Task) { setTasks((current) => current.map((item) => item.id !== task.id ? item : { ...item, status: item.status === 'Pending' ? 'In progress' : 'Completed' })) }
  return <div className="mx-auto max-w-7xl px-6 py-8 sm:px-8 lg:px-10"><header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium text-secondary">Housekeeping</p><h1 className="mt-1 font-display text-2xl font-semibold">Room readiness</h1><p className="mt-1 text-sm text-muted-foreground">Complete room tasks so Reception can assign clean rooms to arriving guests.</p></div><div className="flex rounded-lg border bg-card p-1">{(['All', 'Pending', 'In progress', 'Completed'] as const).map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-md px-3 py-1.5 text-sm font-medium ${filter === value ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`}>{value}</button>)}</div></header><section className="grid gap-4 sm:grid-cols-3"><Metric icon={<LuClipboardList />} label="Tasks pending" value={tasks.filter((task) => task.status === 'Pending').length} /><Metric icon={<LuSparkles />} label="In progress" value={tasks.filter((task) => task.status === 'In progress').length} /><Metric icon={<LuBedDouble />} label="Rooms ready today" value={tasks.filter((task) => task.status === 'Completed').length} /></section><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((task) => <article key={task.id} className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><div><span className="font-display text-xl font-semibold">Room {task.room}</span><p className="mt-1 text-sm text-muted-foreground">{task.type} · {task.id}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${task.status === 'Completed' ? 'bg-success/10 text-success' : task.status === 'In progress' ? 'bg-secondary/10 text-secondary' : 'bg-warning/15 text-warning'}`}>{task.status}</span></div><div className="mt-5 rounded-lg bg-muted/60 p-3 text-sm"><span className="text-muted-foreground">Assigned to</span><p className="mt-1 font-medium">{task.assignee}</p></div>{task.status !== 'Completed' ? <button onClick={() => advance(task)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-primary py-2 text-sm font-medium text-primary-foreground">{task.status === 'Pending' ? 'Start task' : <><LuCheck className="size-4" />Mark room clean</>}</button> : <div className="mt-4 flex items-center justify-center gap-2 rounded-lg bg-success/10 py-2 text-sm font-medium text-success"><LuCheck className="size-4" />Ready for Reception</div>}</article>)}</section></div>
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-xl border bg-card p-4 shadow-sm"><div className="flex items-center gap-2 text-secondary">{icon}<span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</span></div><p className="mt-2 font-display text-2xl font-semibold">{value}</p></div> }
